### PR TITLE
Joe dev

### PR DESCRIPTION
**Pull request by jab2315**
The first push for Rethinking BIM

### CODE REVIEW

**Comment by adamvosburgh** [comment]
Hi Joe - deploying now. Couple quick things for future reference, you have to add the name of the sequence (folder) to the moduleindex.vue, and also the index.md of a sequence should have the sequence name as the slug and title, because that is what will show as the sequence name on the smorgasbord (just a quirk of the site). Attaching screenshots of those changes
Screenshot 2024-08-26 at 11 58 19 AM
Screenshot 2024-08-26 at 11 58 06 AM

**Comment by jab2315** [comment]
Awesome - thanks, Adam - I do not see the other module on the site, though.
Let me know if I need to do anything else on my end!

I'll also be working on module 2 over the weekend, with the hope of
deploying it sometime next week! I'll make sure to include the sequence
info.

**Comment by adamvosburgh** [comment]
Apologies Joe - right after I wrote that I noticed something else that I couldn't solve right away (the branch you were working on was a few commits behind the main branch, and there are a few conflicts that need resolving.) It's no big deal though, will take care of it and have it deployed today.

**Comment by jab2315** [comment]
No worries, thanks for the update!

**Pull request merged**
